---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Macho Verse Dashboard

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Storage:
    style: col
    columns: 1
   # header: false
  Infrastructure:
    style: col
    columns: 1
  Content:
    style: col
    columns: 1
  Utilities:
    style: row
    columns: 2
  Monitoring:
    style: row
    columns: 3
#  Developer:
#    header: false
#  Chat Bots:
#    header: false

headerStyle: boxed
