services:
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - type: bind
        source: ./prometheus-data/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus-data
        target: /prometheus
    deploy:
      mode: global
      # mode: replicated
      # replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "0"
    ports:
     - '3000:3000'
    volumes:
      - type: bind
        source: ./grafana-data
        target: /var/lib/grafana
    depends_on:
      - prometheus
    deploy:
      mode: global
      # mode: replicated
      # replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
volumes:
  prometheus-data:
