services:
  grafana:
    image: grafana/grafana:latest
    user: 0:0
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - traefik
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana-router.rule = ( `grafana.machoboiverse.cloud` )"
        - "traefik.http.routers.grafana-router.entrpoints=websecure"
        - "traefik.http.routers.grafana-router.tls=true"
        - "traefik.http.routers.grafana-router.tls.certresolver=production"
        - "traefik.http.services.grafana-service.loadbalancer.server.port=3000"
  prometheus:
    image: prom/prometheus:v2.51.1
    volumes:
      - ./prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    networks:
      - traefik
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus-router.rule = ( `prometheus.machoboiverse.cloud` )"
        - "traefik.http.routers.prometheus-router.entrpoints=websecure"
        - "traefik.http.routers.prometheus-router.tls=true"
        - "traefik.http.routers.prometheus-router.tls.certresolver=production"
        - "traefik.http.services.prometheus-service.loadbalancer.server.port=9090"

volumes:
  prometheus-data:

networks:
  traefik:
    external: true
