---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.12
    networks:
      - traefik
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
    env_file: .env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host( `homepage.machoboiverse.cloud` )
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.services.homepage-service.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=production

networks:
  traefik:
    external: true
