http:
  routers:
    adguard:
      rule: "Host(`adguard.machoboiverse.cloud`)"
      service: adguard-service
      entryPoints:
        - websecure
      tls:
        certResolver: production

  services:
    adguard-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.10.10.4"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "3s"
