http:
  routers:
    proxmox:
      rule: "Host(`proxmox.machoboiverse.cloud`)"
      service: proxmox-service
      entryPoints:
        - websecure
      tls:
        certResolver: production

  services:
    proxmox-service:
      loadBalancer:
        passHostHeader: true
        serversTransport: "pve"
        servers:
          - url: "https://10.10.10.2:8006"
        healthCheck:
          path: "/#v1:0:18:4:::::::"
          interval: "10s"
          timeout: "3s"
          
  serversTransports:
    pve:
      insecureSkipVerify: true
