---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Macho dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
  # url: "https://b4bz.io"
  # style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  # title: "Demo !"
  # icon: "fa fa-grin"
  # content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: "fas fa-cloud"
    items:
      - name: "TrueNAS Scale"
        logo: "assets/icons/TrueNASScale.webp"
        url: "https://10.10.10.110"
        subtitle: "Store everything"
        keywords: "self hosted nas"
        # target: "button" # optional html a tag target attribute
        tag: "nas"

      - name: "AdGuard Home"
        logo: "assets/icons/AdGuard.svg"
        url: "http://10.10.10.4"
        type: "AdGuardHome"
        tag: "dns"

      - name: "Pi-hole"
        logo: "assets/icons/Pi-hole.png"
        # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        url: "http://10.10.10.5/admin"
        apikey: "a1a490b4469fdb0ffa212c88213f3db126aecb4f0566b7b3af586bd3ea9c9d6c" # optional, needed if web interface is password protected
        type: "PiHole"
        tag: "dns"

      - name: "Proxmox"
        logo: "assets/icons/proxmox.svg"
        url: "https://10.10.10.2:8006"
        api_token: "PVEAPIToken=root@pam!homer=447a4a80-42c6-410a-b3c5-0d7f0413a3eb" 
        hide_decimals: true
        small_font_on_small_screens: true
        type: "Proxmox"
        tag: "vm"

      - name: "qBittorrent"
        logo: "assets/icons/qBittorrent.svg"
        url: "http://10.10.10.3:8080" # Your rTorrent web UI, f.e. ruTorrent or Flood.
        type: "qBittorrent"
        rateInterval: 2000 # Interval for updating the download and upload rates.
        torrentInterval: 5000 # Interval for updating the torrent count.
        target: "_blank" # optional html a tag target attribute
        tag: "torrent"
