global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    # Listen on port 80 for incoming http requests
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    # Listen on port 443 for incoming https requests
    address: :443

# -- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: as096255@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
  production:
    acme:
      email: as096255@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
  cloudflare:
    acme:
      email: as096255@gmail.com
      storage: /etc/traefik/certs/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  tailscale:
    tailscale: {}

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "tcp://socket_proxy:2375"
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.machoboi.cloud`)"
  file:
    directory: /etc/traefik/conf
    watch: true
