---
services:
  traefik:
    image: traefik:v3.0.0
    volumes:
      - ./traefik/:/etc/traefik/:ro
      - ./traefik/conf:/etc/traefik/conf:ro
      - ./traefik/certs:/etc/traefik/certs
    env_file: .env.traefik
    ports:
      - "100.69.69.3:8080:8080"
      - "100.69.69.3:80:80"
      - "100.69.69.3:443:443"
    networks:
      - traefik
      - socket_proxy
    depends_on:
      - socket_proxy
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  socket_proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    networks:
      - socket_proxy
    env_file: .env.socket_proxy
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

networks:
  socket_proxy:
    driver: bridge
  traefik:
    external: true
