services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=speedtest_tracker
      - MYSQL_USER=speedtest
      - MYSQL_PASSWORD=speedtest_tracker
      - TZ=Asia/Kolkata
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

volumes:
  mysql-data:
