- Storage:
    - "TrueNAS Scale":
        href: https://truenas.machoboiverse.cloud
        description: Store everything
        icon: si-truenas-#0095D5
        siteMonitor: https://truenas.machoboiverse.cloud
        widget:
          type: truenas
          url: https://truenas.machoboiverse.cloud
          key: { { HOMEPAGE_VAR_TRUENAS_CORE_API_KEY } }
          enablePools: true
          nasType: scale

- Infrastructure:
    - Proxmox:
        href: https://proxmox.machoboiverse.cloud
        description: Virtualize everything
        icon: si-proxmox-#E57000
        siteMonitor: https://proxmox.machoboiverse.cloud
        widget:
          type: proxmox
          url: https://proxmox.machoboiverse.cloud
          username: { { HOMEPAGE_VAR_PROXMOX_USER } }
          password: { { HOMEPAGE_VAR_PROXMOX_SECRET } }
          node: pve-machoboi # optional

- AI:
    - Open Web UI:
        href: http://10.10.10.3:3000
        description: Chat with your local AI
        ping: open-webui
        icon: http://10.10.10.3:3000/favicon.ico

    - Stable Diffusion Web UI:
        href: http://127.0.0.1:7860
        description: Generate images with your local AI


- Content:
    - qBittorrent:
        href: http://10.10.10.3:8080
        description: Download Torrent
        icon: si-qbittorrent-#2F67BA
        ping: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: { { HOMEPAGE_VAR_QBITTORRENT_USER } }
          password: { { HOMEPAGE_VAR_QBITTORRENT_PASS } }

    - pyload:
        href: https://pyload.machoboiverse.cloud
        description: Download Everything
        icon: https://pyload.machoboiverse.cloud/favicon.ico
        ping: pyload-ng
        widget:
          type: pyload
          url: https://pyload.machoboiverse.cloud
          username: { { HOMEPAGE_VAR_PYLOAD_USER } }
          password: { { HOMEPAGE_VAR_PYLOAD_PASS } }

- Utilities:
    - "AdGuard Home":
        href: https://adguard.machoboiverse.cloud
        description: Primary DNS server
        icon: si-adguard-#68BC71
        siteMonitor: https://adguard.machoboiverse.cloud
        widget:
          type: adguard
          url: https://adguard.machoboiverse.cloud
          username: { { HOMEPAGE_VAR_ADGUARD_API_USER } }
          password: { { HOMEPAGE_VAR_ADGUARD_API_PASS } }
          
    - Pi-Hole:
        href: https://pihole.machoboiverse.cloud/admin
        description: Secondary DNS server
        icon: si-pihole-#96060C
        siteMonitor: https://pihole.machoboiverse.cloud
        widget:
          type: pihole
          url: https://pihole.machoboiverse.cloud
          key: { { HOMEPAGE_VAR_PIHOLE_API_KEY } }

- Monitoring:
    - Prometheus:
        href: http://10.10.10.3:9090
        icon: si-prometheus-#E6522C
        description: Log everyhting
        ping: prometheus
        widget:
          type: prometheus
          url: http://prometheus:9090

    - Grafana:
        href: http://10.10.10.3:3000
        icon: si-grafana-#F46800
        description: Show everyhting
        ping: grafana
        widget:
          type: grafana
          url: http://grafana:3000
          username: { { HOMEPAGE_VAR_GRAFANA_USER } }
          password: { { HOMEPAGE_VAR_GRAFANA_PASS } }

    - "Machoboi Cockpit":
        href: https://machoboi.mudpuppy-hops.ts.net:9090
        description: Monitor The VPS
        icon: si-cockpit-#0066CC
        ping: machoboi.mudpuppy-hops.ts.net

    - "Speedtest Tracker":
        href: https://10.10.10.3:8090
        description: Monitor The Inteernet
        icon: si-speedtest-#0066CC
        ping: speedtest-tracker
        widget:
          type: speedtest
          url: https://speedtest-tracker
